// Code generated by MockGen. DO NOT EDIT.
// Source: managedclustermodule_reconciler.go
//
// Generated by this command:
//
//	mockgen -source=managedclustermodule_reconciler.go -package=hub -destination=mock_managedclustermodule_reconciler.go managedClusterModuleReconcilerHelperAPI
//
// Package hub is a generated GoMock package.
package hub

import (
	context "context"
	reflect "reflect"

	v1beta1 "github.com/kubernetes-sigs/kernel-module-management/api-hub/v1beta1"
	gomock "go.uber.org/mock/gomock"
)

// MockmanagedClusterModuleReconcilerHelperAPI is a mock of managedClusterModuleReconcilerHelperAPI interface.
type MockmanagedClusterModuleReconcilerHelperAPI struct {
	ctrl     *gomock.Controller
	recorder *MockmanagedClusterModuleReconcilerHelperAPIMockRecorder
}

// MockmanagedClusterModuleReconcilerHelperAPIMockRecorder is the mock recorder for MockmanagedClusterModuleReconcilerHelperAPI.
type MockmanagedClusterModuleReconcilerHelperAPIMockRecorder struct {
	mock *MockmanagedClusterModuleReconcilerHelperAPI
}

// NewMockmanagedClusterModuleReconcilerHelperAPI creates a new mock instance.
func NewMockmanagedClusterModuleReconcilerHelperAPI(ctrl *gomock.Controller) *MockmanagedClusterModuleReconcilerHelperAPI {
	mock := &MockmanagedClusterModuleReconcilerHelperAPI{ctrl: ctrl}
	mock.recorder = &MockmanagedClusterModuleReconcilerHelperAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmanagedClusterModuleReconcilerHelperAPI) EXPECT() *MockmanagedClusterModuleReconcilerHelperAPIMockRecorder {
	return m.recorder
}

// handleMIC mocks base method.
func (m *MockmanagedClusterModuleReconcilerHelperAPI) handleMIC(ctx context.Context, mcm *v1beta1.ManagedClusterModule, clusterName string, kernelVersions []string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "handleMIC", ctx, mcm, clusterName, kernelVersions)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// handleMIC indicates an expected call of handleMIC.
func (mr *MockmanagedClusterModuleReconcilerHelperAPIMockRecorder) handleMIC(ctx, mcm, clusterName, kernelVersions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "handleMIC", reflect.TypeOf((*MockmanagedClusterModuleReconcilerHelperAPI)(nil).handleMIC), ctx, mcm, clusterName, kernelVersions)
}
