@startuml
'https://plantuml.com/activity-diagram-beta

title ""Module"" Reconciliation

start

:""Reconcile()"";

:Fetch all (node, kernel) pairs that
match the ""Module""'s top-level ""selector"";

repeat :Loop over matching nodes;
    ->next node;
    note
        Pair each node requiring the ""Module""
        with a DriverContainer image
        that works with its kernel
    end note
    repeat :Loop over the Module's kernel mappings;
        ->next kernel mapping;
        if (does the kernel mapping match the node's kernel?) then (yes)
            :Add the DaemonSet to the list;
            note: We select the first\nmatching mapping.
            break
        else (no)
        endif
    repeat while (Any kernel mapping left?) is (yes) not (no)
repeat while (Any node left?) is (yes) not (no)

if (Is the list of DaemonSets empty?) then (no)
    :Reconcile those DaemonSets;
else (yes)
endif

stop

@enduml