apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: kmm
spec:
  collectors:
    - clusterInfo: {}
    - clusterResources:
        #FIXME: remove to collect resources from all namespaces?
        namespaces:
          - default
          - cert-manager
          - kmm-operator-system
          - olm
          - operators
    - logs:
        namespace: kmm-operator-system
        selector:
          - app.kubernetes.io/part-of=kmm
    - logs:
        namespace: olm
    - logs:
        namespace: operators
  hostCollectors:
    - cpu: {}
    - hostOS: {}
    - http:
        get:
          url: http://localhost:5000/v2/_catalog
    - memory: {}
    - run:
        collectorName: "kernel logs"
        command: "dmesg"
        args: []
  analyzers:
    #
    # cert-manager Deployments
    #
    - deploymentStatus:
        name: cert-manager
        namespace: cert-manager
        outcomes:
          - fail:
              when: "absent"
              message: The deployment is not present.
          - fail:
              when: "< 1"
              message: The deployment does not have any ready replicas.
          - pass:
              message: There is at least one Ready replica of the Deployment.
    - deploymentStatus:
        name: cert-manager-cainjector
        namespace: cert-manager
        outcomes:
          - fail:
              when: "absent"
              message: The deployment is not present.
          - fail:
              when: "< 1"
              message: The deployment does not have any ready replicas.
          - pass:
              message: There is at least one Ready replica of the Deployment.
    - deploymentStatus:
        name: cert-manager-webhook
        namespace: cert-manager
        outcomes:
          - fail:
              when: "absent"
              message: The deployment is not present.
          - fail:
              when: "< 1"
              message: The deployment does not have any ready replicas.
          - pass:
              message: There is at least one Ready replica of the Deployment.
    #
    # KMM Deployments
    #
    - deploymentStatus:
        name: kmm-operator-controller
        namespace: kmm-operator-system
        outcomes:
          - fail:
              when: "absent"
              message: The KMM deployment is not present.
          - fail:
              when: "< 1"
              message: The API deployment does not have any ready replicas.
          - pass:
              message: There is at least one Ready replica of the Deployment.
    - deploymentStatus:
        name: kmm-operator-hub-controller
        namespace: kmm-operator-system
        outcomes:
          - fail:
              when: "absent"
              message: The KMM-Hub deployment is not present.
          - fail:
              when: "< 1"
              message: The API deployment does not have any ready replicas.
          - pass:
              message: There is at least one Ready replica of the Deployment.
    - clusterPodStatuses:
        namespace: default
        outcomes:
          - fail:
              # Catch all unhealthy pods. A pod is considered healthy if it has a status of Completed,
              # or Running and all of its containers are ready.
              when: "!= Healthy"
                # {{ .Status.Reason }} displays the current status of the pod, while {{ .Status.Message }}
                # provides a detailed explanation of why the pod is unhealthy, based on logged events.
              message: Pod {{ .Namespace }}/{{ .Name }} is unhealthy with a status of {{ .Status.Reason }}. Message is {{ .Status.Message }}
