apiVersion: kmm.sigs.k8s.io/v1beta1
kind: Module
metadata:
  name: kmm-ci-a
spec:
  driverContainer:
    container:
      modprobe:
        moduleName: kmm-ci-a 

      kernelMappings:
        - literal: 5.4.196-108.356.amzn2.x86_64
          containerImage: 804517629211.dkr.ecr.eu-west-3.amazonaws.com/kmm-kmod:1.0-dkms
          build:
            buildArgs:
              - name: CI_BUILD_ARG
                value: some-build-arg
            dockerfile: |
              ARG KERNEL_VERSION=''
              FROM amazonlinux as builder
              RUN amazon-linux-extras install kernel-5.4 -y
              RUN yum -y install dkms \ 
                  kernel-headers-5.4.196-108.356.amzn2.x86_64 \
                  kernel-5.4.196-108.356.amzn2.x86_64 \
                  kernel-devel-5.4.196-108.356.amzn2.x86_64 \
                  python3 \
                  git \
                  make \
                  gcc \
                  bison \
                  flex \
                  elfutils-libelf-devel \
                  linux-headers \
                  openssl-devel \
                  xz \
                  yum-utils \
                  bc && \
                  yum clean all

              WORKDIR /usr/src
              RUN git clone https://github.com/kubernetes-sigs/kernel-module-management.git && \
                  mv kernel-module-management/ci/kmm-kmod kmm-kmod-0.0.1 && \
                  dkms add kmm-kmod/0.0.1 && \
                  dkms build kmm-kmod/0.0.1 && \
                  dkms install kmm-kmod/0.0.1
    
              ARG KERNEL_VERSION
              FROM amazonlinux
              RUN yum -y install kmod && yum clean all
              COPY --from=builder /lib/modules/5.4.196-108.356.amzn2.x86_64/kernel/drivers/other/kmm/ /opt/lib/modules/${KERNEL_VERSION}/
              RUN depmod -b /opt
    imageRepoSecret: 
      name: aws-repo-secret  
  selector:  
    kubernetes.io/hostname: ip-192-168-13-20.eu-west-3.compute.internal

