@startuml

title ""Node"" reconciliation

skinparam ConditionEndStyle hline

start

:""Reconcile()"";

:Get all ""Module""s;

repeat :Loop over unprocessed modules;
    ->next ""Module"";
    if (Does the ""Module""'s top-level\nselector match the node?) then (no)
        break
    else (yes)
        repeat :Loop over the Module's kernel mappings;
            ->next kernel mapping;
            if (does the kernel mapping match the node's kernel?) then (yes)
                :Add the DaemonSet to the list;
                note: We select the first\nmatching mapping.
                break
            else (no)
            endif
        repeat while (Any kernel mapping left?) is (yes) not (no)
    endif
repeat while (Any ""Module"" left?) is (yes) not (no)

if (Is the list of DaemonSets empty?) then (no)
    :Reconcile those DaemonSets;
else (yes)
endif

stop

@enduml
