FROM alpine:3.21 as ksource

RUN ["apk", "add", "linux-virt-dev"]

FROM alpine:3.21

COPY --from=ksource /usr/src/linux-headers-*-virt/scripts/sign-file /usr/local/bin/sign-file

ENTRYPOINT ["/usr/local/bin/sign-file"]
