apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../manager-base

patches:
- path: manager_worker_image_patch.yaml

images:
- name: controller
  newName: host.minikube.internal:5000/kmm
- name: worker
  newName: host.minikube.internal:5000/kmm-worker

configMapGenerator:
- files:
  - controller_config.yaml
  name: manager-config

generatorOptions:
  disableNameSuffixHash: true
