apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- certificate.yaml

configurations:
- kustomizeconfig.yaml

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: webhook-server
      namespace: system
    spec:
      template:
        spec:
          containers:
            - name: webhook-server
              volumeMounts:
                - mountPath: /tmp/k8s-webhook-server/serving-certs
                  name: cert
                  readOnly: true
          volumes:
            - name: cert
              secret:
                defaultMode: 420
                secretName: webhook-server-cert

