apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

images:
- name: signer
  newName: gcr.io/k8s-staging-kmm/kernel-module-management-signimage
  newTag: latest

patches:
# Protect the /metrics endpoint by putting it behind auth.
# If you want your controller-manager to expose the /metrics
# endpoint w/o any authn/z, please comment the following line.
- path: manager_auth_proxy_patch.yaml

# Mount the controller config file for loading manager configurations
# through a ComponentConfig type
- path: manager_config_patch.yaml

configurations:
- kustomizeconfig.yaml
