apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        args:
        - "--config=controller_config.yaml"
        volumeMounts:
        - name: manager-config
          mountPath: /controller_config.yaml
          subPath: controller_config.yaml
      volumes:
      - name: manager-config
        configMap:
          name: manager-config
