// Code generated by MockGen. DO NOT EDIT.
// Source: statusupdater.go

// Package statusupdater is a generated GoMock package.
package statusupdater

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1alpha1 "github.com/qbarrand/oot-operator/api/v1alpha1"
	v1 "k8s.io/api/apps/v1"
	v10 "k8s.io/api/core/v1"
)

// MockModuleStatusUpdater is a mock of ModuleStatusUpdater interface.
type MockModuleStatusUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockModuleStatusUpdaterMockRecorder
}

// MockModuleStatusUpdaterMockRecorder is the mock recorder for MockModuleStatusUpdater.
type MockModuleStatusUpdaterMockRecorder struct {
	mock *MockModuleStatusUpdater
}

// NewMockModuleStatusUpdater creates a new mock instance.
func NewMockModuleStatusUpdater(ctrl *gomock.Controller) *MockModuleStatusUpdater {
	mock := &MockModuleStatusUpdater{ctrl: ctrl}
	mock.recorder = &MockModuleStatusUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModuleStatusUpdater) EXPECT() *MockModuleStatusUpdaterMockRecorder {
	return m.recorder
}

// ModuleUpdateStatus mocks base method.
func (m *MockModuleStatusUpdater) ModuleUpdateStatus(ctx context.Context, mod *v1alpha1.Module, kernelMappingNodes, targetedNodes []v10.Node, dsByKernelVersion map[string]*v1.DaemonSet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModuleUpdateStatus", ctx, mod, kernelMappingNodes, targetedNodes, dsByKernelVersion)
	ret0, _ := ret[0].(error)
	return ret0
}

// ModuleUpdateStatus indicates an expected call of ModuleUpdateStatus.
func (mr *MockModuleStatusUpdaterMockRecorder) ModuleUpdateStatus(ctx, mod, kernelMappingNodes, targetedNodes, dsByKernelVersion interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModuleUpdateStatus", reflect.TypeOf((*MockModuleStatusUpdater)(nil).ModuleUpdateStatus), ctx, mod, kernelMappingNodes, targetedNodes, dsByKernelVersion)
}

// MockPreflightStatusUpdater is a mock of PreflightStatusUpdater interface.
type MockPreflightStatusUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockPreflightStatusUpdaterMockRecorder
}

// MockPreflightStatusUpdaterMockRecorder is the mock recorder for MockPreflightStatusUpdater.
type MockPreflightStatusUpdaterMockRecorder struct {
	mock *MockPreflightStatusUpdater
}

// NewMockPreflightStatusUpdater creates a new mock instance.
func NewMockPreflightStatusUpdater(ctrl *gomock.Controller) *MockPreflightStatusUpdater {
	mock := &MockPreflightStatusUpdater{ctrl: ctrl}
	mock.recorder = &MockPreflightStatusUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreflightStatusUpdater) EXPECT() *MockPreflightStatusUpdaterMockRecorder {
	return m.recorder
}

// PreflightPresetVerificationStatus mocks base method.
func (m *MockPreflightStatusUpdater) PreflightPresetVerificationStatus(ctx context.Context, pv *v1alpha1.PreflightValidation, status *v1alpha1.CRStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreflightPresetVerificationStatus", ctx, pv, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// PreflightPresetVerificationStatus indicates an expected call of PreflightPresetVerificationStatus.
func (mr *MockPreflightStatusUpdaterMockRecorder) PreflightPresetVerificationStatus(ctx, pv, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreflightPresetVerificationStatus", reflect.TypeOf((*MockPreflightStatusUpdater)(nil).PreflightPresetVerificationStatus), ctx, pv, status)
}

// PreflightSetVerificationStage mocks base method.
func (m *MockPreflightStatusUpdater) PreflightSetVerificationStage(ctx context.Context, preflight *v1alpha1.PreflightValidation, status *v1alpha1.CRStatus, stage string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreflightSetVerificationStage", ctx, preflight, status, stage)
	ret0, _ := ret[0].(error)
	return ret0
}

// PreflightSetVerificationStage indicates an expected call of PreflightSetVerificationStage.
func (mr *MockPreflightStatusUpdaterMockRecorder) PreflightSetVerificationStage(ctx, preflight, status, stage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreflightSetVerificationStage", reflect.TypeOf((*MockPreflightStatusUpdater)(nil).PreflightSetVerificationStage), ctx, preflight, status, stage)
}

// PreflightSetVerificationStatus mocks base method.
func (m *MockPreflightStatusUpdater) PreflightSetVerificationStatus(ctx context.Context, preflight *v1alpha1.PreflightValidation, status *v1alpha1.CRStatus, verificationStatus, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreflightSetVerificationStatus", ctx, preflight, status, verificationStatus, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// PreflightSetVerificationStatus indicates an expected call of PreflightSetVerificationStatus.
func (mr *MockPreflightStatusUpdaterMockRecorder) PreflightSetVerificationStatus(ctx, preflight, status, verificationStatus, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreflightSetVerificationStatus", reflect.TypeOf((*MockPreflightStatusUpdater)(nil).PreflightSetVerificationStatus), ctx, preflight, status, verificationStatus, message)
}
