healthProbeBindAddress: :8081
webhookPort: 9443
metrics:
  enableAuthnAuthz: true
  bindAddress: 0.0.0.0:8443
  secureServing: true
worker:
  runAsUser: 0
  seLinuxType: spc_t
  setFirmwareClassPath: /var/lib/firmware
