apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../config/default

images:
- name: gcr.io/k8s-staging-kmm/kernel-module-management-operator
  newName: kmm
  newTag: local
- name: gcr.io/k8s-staging-kmm/kernel-module-management-signimage
  newName: host.minikube.internal:5000/kmm/signimage
  newTag: local
- name: gcr.io/k8s-staging-kmm/kernel-module-management-webhook-server
  newName: kmm-webhook-server
  newTag: local
- name: gcr.io/k8s-staging-kmm/kernel-module-management-worker
  newName: kmm-worker
  newTag: local

patches:
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: controller
      namespace: system
    spec:
      template:
        spec:
          containers:
            - name: manager
              imagePullPolicy: Never
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: webhook
      namespace: system
    spec:
      template:
        spec:
          containers:
            - name: webhook-server
              imagePullPolicy: Never
