apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../config/default

images:
- name: gcr.io/k8s-staging-kmm/kernel-module-management-operator
  newName: kmm
  newTag: local

patches:
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: controller
      namespace: system
    spec:
      template:
        spec:
          containers:
            - name: manager
              imagePullPolicy: Never
              env:
                - name: RELATED_IMAGE_SIGN
                  value: host.minikube.internal:5000/kmm/signimage:local
                - name: RELATED_IMAGE_WORKER
                  value: host.minikube.internal:5000/kmm/worker:local
