apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kmm-hub.namePrefix" . }}controller
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller
    {{- include "kmm-hub.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      control-plane: controller
      {{- include "kmm-hub.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.controller.replicas }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller
        {{- include "kmm-hub.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
          - weight: 1
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
      securityContext:
        runAsNonRoot: true
      containers:
      - image: {{ .Values.controller.image }}
        {{- if .Values.controller.imagePullPolicy }}
        imagePullPolicy: {{ .Values.controller.imagePullPolicy }}
        {{- end }}
        name: manager
        args:
          - "--config={{ .Values.controller.managerConfig }}"
        env:
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: RELATED_IMAGE_BUILD
            value: {{ .Values.controller.buildImage }}
          - name: RELATED_IMAGE_SIGN
            value: {{ .Values.controller.signerImage }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: [ALL]
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        ports:
          - name: https
            containerPort: 8443
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.controller.resources | nindent 10 }}
      serviceAccountName: {{ include "kmm-hub.namePrefix" . }}controller
      terminationGracePeriodSeconds: 10
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Equal
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          operator: Equal
          effect: NoSchedule
