apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service.yaml
- manifests.yaml

configurations:
- kustomizeconfig.yaml

patches:
- path: manifests_namespace_selector_patch.yaml
