apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: kmm-operator-

# Labels to add to all resources and selectors.

# These resources constitute the fully configured set of manifests
# used to generate the 'manifests/' directory in a bundle.
resources:
- ../deploy
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: kmm
    app.kubernetes.io/name: kmm
    app.kubernetes.io/part-of: kmm
