// Code generated by MockGen. DO NOT EDIT.
// Source: factory.go

// Package api is a generated GoMock package.
package api

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1beta1 "github.com/kubernetes-sigs/kernel-module-management/api/v1beta1"
)

// MockModuleLoaderDataFactory is a mock of ModuleLoaderDataFactory interface.
type MockModuleLoaderDataFactory struct {
	ctrl     *gomock.Controller
	recorder *MockModuleLoaderDataFactoryMockRecorder
}

// MockModuleLoaderDataFactoryMockRecorder is the mock recorder for MockModuleLoaderDataFactory.
type MockModuleLoaderDataFactoryMockRecorder struct {
	mock *MockModuleLoaderDataFactory
}

// NewMockModuleLoaderDataFactory creates a new mock instance.
func NewMockModuleLoaderDataFactory(ctrl *gomock.Controller) *MockModuleLoaderDataFactory {
	mock := &MockModuleLoaderDataFactory{ctrl: ctrl}
	mock.recorder = &MockModuleLoaderDataFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModuleLoaderDataFactory) EXPECT() *MockModuleLoaderDataFactoryMockRecorder {
	return m.recorder
}

// FromModule mocks base method.
func (m *MockModuleLoaderDataFactory) FromModule(mod *v1beta1.Module, kernelVersion string) (*ModuleLoaderData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FromModule", mod, kernelVersion)
	ret0, _ := ret[0].(*ModuleLoaderData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FromModule indicates an expected call of FromModule.
func (mr *MockModuleLoaderDataFactoryMockRecorder) FromModule(mod, kernelVersion interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FromModule", reflect.TypeOf((*MockModuleLoaderDataFactory)(nil).FromModule), mod, kernelVersion)
}

// MockmoduleLoaderDataFactoryHelper is a mock of moduleLoaderDataFactoryHelper interface.
type MockmoduleLoaderDataFactoryHelper struct {
	ctrl     *gomock.Controller
	recorder *MockmoduleLoaderDataFactoryHelperMockRecorder
}

// MockmoduleLoaderDataFactoryHelperMockRecorder is the mock recorder for MockmoduleLoaderDataFactoryHelper.
type MockmoduleLoaderDataFactoryHelperMockRecorder struct {
	mock *MockmoduleLoaderDataFactoryHelper
}

// NewMockmoduleLoaderDataFactoryHelper creates a new mock instance.
func NewMockmoduleLoaderDataFactoryHelper(ctrl *gomock.Controller) *MockmoduleLoaderDataFactoryHelper {
	mock := &MockmoduleLoaderDataFactoryHelper{ctrl: ctrl}
	mock.recorder = &MockmoduleLoaderDataFactoryHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmoduleLoaderDataFactoryHelper) EXPECT() *MockmoduleLoaderDataFactoryHelperMockRecorder {
	return m.recorder
}

// findKernelMapping mocks base method.
func (m *MockmoduleLoaderDataFactoryHelper) findKernelMapping(mappings []v1beta1.KernelMapping, kernelVersion string) (*v1beta1.KernelMapping, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "findKernelMapping", mappings, kernelVersion)
	ret0, _ := ret[0].(*v1beta1.KernelMapping)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// findKernelMapping indicates an expected call of findKernelMapping.
func (mr *MockmoduleLoaderDataFactoryHelperMockRecorder) findKernelMapping(mappings, kernelVersion interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "findKernelMapping", reflect.TypeOf((*MockmoduleLoaderDataFactoryHelper)(nil).findKernelMapping), mappings, kernelVersion)
}

// prepareModuleLoaderData mocks base method.
func (m *MockmoduleLoaderDataFactoryHelper) prepareModuleLoaderData(mapping *v1beta1.KernelMapping, mod *v1beta1.Module, kernelVersion string) (*ModuleLoaderData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "prepareModuleLoaderData", mapping, mod, kernelVersion)
	ret0, _ := ret[0].(*ModuleLoaderData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// prepareModuleLoaderData indicates an expected call of prepareModuleLoaderData.
func (mr *MockmoduleLoaderDataFactoryHelperMockRecorder) prepareModuleLoaderData(mapping, mod, kernelVersion interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "prepareModuleLoaderData", reflect.TypeOf((*MockmoduleLoaderDataFactoryHelper)(nil).prepareModuleLoaderData), mapping, mod, kernelVersion)
}

// replaceTemplates mocks base method.
func (m *MockmoduleLoaderDataFactoryHelper) replaceTemplates(mld *ModuleLoaderData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "replaceTemplates", mld)
	ret0, _ := ret[0].(error)
	return ret0
}

// replaceTemplates indicates an expected call of replaceTemplates.
func (mr *MockmoduleLoaderDataFactoryHelperMockRecorder) replaceTemplates(mld interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "replaceTemplates", reflect.TypeOf((*MockmoduleLoaderDataFactoryHelper)(nil).replaceTemplates), mld)
}

// MocksectionGetter is a mock of sectionGetter interface.
type MocksectionGetter struct {
	ctrl     *gomock.Controller
	recorder *MocksectionGetterMockRecorder
}

// MocksectionGetterMockRecorder is the mock recorder for MocksectionGetter.
type MocksectionGetterMockRecorder struct {
	mock *MocksectionGetter
}

// NewMocksectionGetter creates a new mock instance.
func NewMocksectionGetter(ctrl *gomock.Controller) *MocksectionGetter {
	mock := &MocksectionGetter{ctrl: ctrl}
	mock.recorder = &MocksectionGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksectionGetter) EXPECT() *MocksectionGetterMockRecorder {
	return m.recorder
}

// GetRelevantBuild mocks base method.
func (m *MocksectionGetter) GetRelevantBuild(moduleBuild, mappingBuild *v1beta1.Build) *v1beta1.Build {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelevantBuild", moduleBuild, mappingBuild)
	ret0, _ := ret[0].(*v1beta1.Build)
	return ret0
}

// GetRelevantBuild indicates an expected call of GetRelevantBuild.
func (mr *MocksectionGetterMockRecorder) GetRelevantBuild(moduleBuild, mappingBuild interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelevantBuild", reflect.TypeOf((*MocksectionGetter)(nil).GetRelevantBuild), moduleBuild, mappingBuild)
}

// GetRelevantSign mocks base method.
func (m *MocksectionGetter) GetRelevantSign(moduleSign, mappingSign *v1beta1.Sign, kernel string) (*v1beta1.Sign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelevantSign", moduleSign, mappingSign, kernel)
	ret0, _ := ret[0].(*v1beta1.Sign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelevantSign indicates an expected call of GetRelevantSign.
func (mr *MocksectionGetterMockRecorder) GetRelevantSign(moduleSign, mappingSign, kernel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelevantSign", reflect.TypeOf((*MocksectionGetter)(nil).GetRelevantSign), moduleSign, mappingSign, kernel)
}
