// Code generated by MockGen. DO NOT EDIT.
// Source: dra_reconciler.go
//
// Generated by this command:
//
//	mockgen -source=dra_reconciler.go -package=controllers -destination=mock_dra_reconciler.go draReconcilerHelperAPI,draDaemonSetCreator
//
// Package controllers is a generated GoMock package.
package controllers

import (
	context "context"
	reflect "reflect"

	v1beta1 "github.com/kubernetes-sigs/kernel-module-management/api/v1beta1"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/apps/v1"
	v10 "k8s.io/api/resource/v1"
)

// MockdraReconcilerHelperAPI is a mock of draReconcilerHelperAPI interface.
type MockdraReconcilerHelperAPI struct {
	ctrl     *gomock.Controller
	recorder *MockdraReconcilerHelperAPIMockRecorder
}

// MockdraReconcilerHelperAPIMockRecorder is the mock recorder for MockdraReconcilerHelperAPI.
type MockdraReconcilerHelperAPIMockRecorder struct {
	mock *MockdraReconcilerHelperAPI
}

// NewMockdraReconcilerHelperAPI creates a new mock instance.
func NewMockdraReconcilerHelperAPI(ctrl *gomock.Controller) *MockdraReconcilerHelperAPI {
	mock := &MockdraReconcilerHelperAPI{ctrl: ctrl}
	mock.recorder = &MockdraReconcilerHelperAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdraReconcilerHelperAPI) EXPECT() *MockdraReconcilerHelperAPIMockRecorder {
	return m.recorder
}

// clearDRAStatus mocks base method.
func (m *MockdraReconcilerHelperAPI) clearDRAStatus(ctx context.Context, mod *v1beta1.Module) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "clearDRAStatus", ctx, mod)
	ret0, _ := ret[0].(error)
	return ret0
}

// clearDRAStatus indicates an expected call of clearDRAStatus.
func (mr *MockdraReconcilerHelperAPIMockRecorder) clearDRAStatus(ctx, mod any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "clearDRAStatus", reflect.TypeOf((*MockdraReconcilerHelperAPI)(nil).clearDRAStatus), ctx, mod)
}

// deleteDRAResources mocks base method.
func (m *MockdraReconcilerHelperAPI) deleteDRAResources(ctx context.Context, moduleName, moduleNamespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "deleteDRAResources", ctx, moduleName, moduleNamespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// deleteDRAResources indicates an expected call of deleteDRAResources.
func (mr *MockdraReconcilerHelperAPIMockRecorder) deleteDRAResources(ctx, moduleName, moduleNamespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "deleteDRAResources", reflect.TypeOf((*MockdraReconcilerHelperAPI)(nil).deleteDRAResources), ctx, moduleName, moduleNamespace)
}

// garbageCollectDRADaemonSets mocks base method.
func (m *MockdraReconcilerHelperAPI) garbageCollectDRADaemonSets(ctx context.Context, mod *v1beta1.Module, existingDS []v1.DaemonSet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "garbageCollectDRADaemonSets", ctx, mod, existingDS)
	ret0, _ := ret[0].(error)
	return ret0
}

// garbageCollectDRADaemonSets indicates an expected call of garbageCollectDRADaemonSets.
func (mr *MockdraReconcilerHelperAPIMockRecorder) garbageCollectDRADaemonSets(ctx, mod, existingDS any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "garbageCollectDRADaemonSets", reflect.TypeOf((*MockdraReconcilerHelperAPI)(nil).garbageCollectDRADaemonSets), ctx, mod, existingDS)
}

// getModuleDRADaemonSets mocks base method.
func (m *MockdraReconcilerHelperAPI) getModuleDRADaemonSets(ctx context.Context, name, namespace string) ([]v1.DaemonSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getModuleDRADaemonSets", ctx, name, namespace)
	ret0, _ := ret[0].([]v1.DaemonSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getModuleDRADaemonSets indicates an expected call of getModuleDRADaemonSets.
func (mr *MockdraReconcilerHelperAPIMockRecorder) getModuleDRADaemonSets(ctx, name, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getModuleDRADaemonSets", reflect.TypeOf((*MockdraReconcilerHelperAPI)(nil).getModuleDRADaemonSets), ctx, name, namespace)
}

// getModuleDeviceClasses mocks base method.
func (m *MockdraReconcilerHelperAPI) getModuleDeviceClasses(ctx context.Context, name, namespace string) ([]v10.DeviceClass, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getModuleDeviceClasses", ctx, name, namespace)
	ret0, _ := ret[0].([]v10.DeviceClass)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getModuleDeviceClasses indicates an expected call of getModuleDeviceClasses.
func (mr *MockdraReconcilerHelperAPIMockRecorder) getModuleDeviceClasses(ctx, name, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getModuleDeviceClasses", reflect.TypeOf((*MockdraReconcilerHelperAPI)(nil).getModuleDeviceClasses), ctx, name, namespace)
}

// handleDRA mocks base method.
func (m *MockdraReconcilerHelperAPI) handleDRA(ctx context.Context, mod *v1beta1.Module, existingDRADS []v1.DaemonSet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "handleDRA", ctx, mod, existingDRADS)
	ret0, _ := ret[0].(error)
	return ret0
}

// handleDRA indicates an expected call of handleDRA.
func (mr *MockdraReconcilerHelperAPIMockRecorder) handleDRA(ctx, mod, existingDRADS any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "handleDRA", reflect.TypeOf((*MockdraReconcilerHelperAPI)(nil).handleDRA), ctx, mod, existingDRADS)
}

// handleDeviceClasses mocks base method.
func (m *MockdraReconcilerHelperAPI) handleDeviceClasses(ctx context.Context, mod *v1beta1.Module, existingDCs []v10.DeviceClass) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "handleDeviceClasses", ctx, mod, existingDCs)
	ret0, _ := ret[0].(error)
	return ret0
}

// handleDeviceClasses indicates an expected call of handleDeviceClasses.
func (mr *MockdraReconcilerHelperAPIMockRecorder) handleDeviceClasses(ctx, mod, existingDCs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "handleDeviceClasses", reflect.TypeOf((*MockdraReconcilerHelperAPI)(nil).handleDeviceClasses), ctx, mod, existingDCs)
}

// moduleUpdateDRAStatus mocks base method.
func (m *MockdraReconcilerHelperAPI) moduleUpdateDRAStatus(ctx context.Context, mod *v1beta1.Module, existingDRADS []v1.DaemonSet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "moduleUpdateDRAStatus", ctx, mod, existingDRADS)
	ret0, _ := ret[0].(error)
	return ret0
}

// moduleUpdateDRAStatus indicates an expected call of moduleUpdateDRAStatus.
func (mr *MockdraReconcilerHelperAPIMockRecorder) moduleUpdateDRAStatus(ctx, mod, existingDRADS any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "moduleUpdateDRAStatus", reflect.TypeOf((*MockdraReconcilerHelperAPI)(nil).moduleUpdateDRAStatus), ctx, mod, existingDRADS)
}

// MockdraDaemonSetCreator is a mock of draDaemonSetCreator interface.
type MockdraDaemonSetCreator struct {
	ctrl     *gomock.Controller
	recorder *MockdraDaemonSetCreatorMockRecorder
}

// MockdraDaemonSetCreatorMockRecorder is the mock recorder for MockdraDaemonSetCreator.
type MockdraDaemonSetCreatorMockRecorder struct {
	mock *MockdraDaemonSetCreator
}

// NewMockdraDaemonSetCreator creates a new mock instance.
func NewMockdraDaemonSetCreator(ctrl *gomock.Controller) *MockdraDaemonSetCreator {
	mock := &MockdraDaemonSetCreator{ctrl: ctrl}
	mock.recorder = &MockdraDaemonSetCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdraDaemonSetCreator) EXPECT() *MockdraDaemonSetCreatorMockRecorder {
	return m.recorder
}

// setDRAAsDesired mocks base method.
func (m *MockdraDaemonSetCreator) setDRAAsDesired(ctx context.Context, ds *v1.DaemonSet, mod *v1beta1.Module) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "setDRAAsDesired", ctx, ds, mod)
	ret0, _ := ret[0].(error)
	return ret0
}

// setDRAAsDesired indicates an expected call of setDRAAsDesired.
func (mr *MockdraDaemonSetCreatorMockRecorder) setDRAAsDesired(ctx, ds, mod any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "setDRAAsDesired", reflect.TypeOf((*MockdraDaemonSetCreator)(nil).setDRAAsDesired), ctx, ds, mod)
}
