// Code generated by MockGen. DO NOT EDIT.
// Source: dra_reconciler.go
//
// Generated by this command:
//
//	mockgen -source=dra_reconciler.go -package=controllers -destination=mock_dra_reconciler.go draReconcilerHelperAPI,draDaemonSetCreator
//
// Package controllers is a generated GoMock package.
package controllers

import (
	context "context"
	reflect "reflect"

	v1beta1 "github.com/kubernetes-sigs/kernel-module-management/api/v1beta1"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/apps/v1"
)

// MockdraReconcilerHelperAPI is a mock of draReconcilerHelperAPI interface.
type MockdraReconcilerHelperAPI struct {
	ctrl     *gomock.Controller
	recorder *MockdraReconcilerHelperAPIMockRecorder
}

// MockdraReconcilerHelperAPIMockRecorder is the mock recorder for MockdraReconcilerHelperAPI.
type MockdraReconcilerHelperAPIMockRecorder struct {
	mock *MockdraReconcilerHelperAPI
}

// NewMockdraReconcilerHelperAPI creates a new mock instance.
func NewMockdraReconcilerHelperAPI(ctrl *gomock.Controller) *MockdraReconcilerHelperAPI {
	mock := &MockdraReconcilerHelperAPI{ctrl: ctrl}
	mock.recorder = &MockdraReconcilerHelperAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdraReconcilerHelperAPI) EXPECT() *MockdraReconcilerHelperAPIMockRecorder {
	return m.recorder
}

// clearDRAStatus mocks base method.
func (m *MockdraReconcilerHelperAPI) clearDRAStatus(ctx context.Context, mod *v1beta1.Module) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "clearDRAStatus", ctx, mod)
	ret0, _ := ret[0].(error)
	return ret0
}

// clearDRAStatus indicates an expected call of clearDRAStatus.
func (mr *MockdraReconcilerHelperAPIMockRecorder) clearDRAStatus(ctx, mod any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "clearDRAStatus", reflect.TypeOf((*MockdraReconcilerHelperAPI)(nil).clearDRAStatus), ctx, mod)
}

// deleteDRADaemonSets mocks base method.
func (m *MockdraReconcilerHelperAPI) deleteDRADaemonSets(ctx context.Context, existingDRADS []v1.DaemonSet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "deleteDRADaemonSets", ctx, existingDRADS)
	ret0, _ := ret[0].(error)
	return ret0
}

// deleteDRADaemonSets indicates an expected call of deleteDRADaemonSets.
func (mr *MockdraReconcilerHelperAPIMockRecorder) deleteDRADaemonSets(ctx, existingDRADS any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "deleteDRADaemonSets", reflect.TypeOf((*MockdraReconcilerHelperAPI)(nil).deleteDRADaemonSets), ctx, existingDRADS)
}

// getModuleDRADaemonSets mocks base method.
func (m *MockdraReconcilerHelperAPI) getModuleDRADaemonSets(ctx context.Context, name, namespace string) ([]v1.DaemonSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getModuleDRADaemonSets", ctx, name, namespace)
	ret0, _ := ret[0].([]v1.DaemonSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getModuleDRADaemonSets indicates an expected call of getModuleDRADaemonSets.
func (mr *MockdraReconcilerHelperAPIMockRecorder) getModuleDRADaemonSets(ctx, name, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getModuleDRADaemonSets", reflect.TypeOf((*MockdraReconcilerHelperAPI)(nil).getModuleDRADaemonSets), ctx, name, namespace)
}

// handleDRA mocks base method.
func (m *MockdraReconcilerHelperAPI) handleDRA(ctx context.Context, mod *v1beta1.Module, existingDRADS []v1.DaemonSet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "handleDRA", ctx, mod, existingDRADS)
	ret0, _ := ret[0].(error)
	return ret0
}

// handleDRA indicates an expected call of handleDRA.
func (mr *MockdraReconcilerHelperAPIMockRecorder) handleDRA(ctx, mod, existingDRADS any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "handleDRA", reflect.TypeOf((*MockdraReconcilerHelperAPI)(nil).handleDRA), ctx, mod, existingDRADS)
}

// moduleUpdateDRAStatus mocks base method.
func (m *MockdraReconcilerHelperAPI) moduleUpdateDRAStatus(ctx context.Context, mod *v1beta1.Module, existingDRADS []v1.DaemonSet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "moduleUpdateDRAStatus", ctx, mod, existingDRADS)
	ret0, _ := ret[0].(error)
	return ret0
}

// moduleUpdateDRAStatus indicates an expected call of moduleUpdateDRAStatus.
func (mr *MockdraReconcilerHelperAPIMockRecorder) moduleUpdateDRAStatus(ctx, mod, existingDRADS any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "moduleUpdateDRAStatus", reflect.TypeOf((*MockdraReconcilerHelperAPI)(nil).moduleUpdateDRAStatus), ctx, mod, existingDRADS)
}

// MockdraDaemonSetCreator is a mock of draDaemonSetCreator interface.
type MockdraDaemonSetCreator struct {
	ctrl     *gomock.Controller
	recorder *MockdraDaemonSetCreatorMockRecorder
}

// MockdraDaemonSetCreatorMockRecorder is the mock recorder for MockdraDaemonSetCreator.
type MockdraDaemonSetCreatorMockRecorder struct {
	mock *MockdraDaemonSetCreator
}

// NewMockdraDaemonSetCreator creates a new mock instance.
func NewMockdraDaemonSetCreator(ctrl *gomock.Controller) *MockdraDaemonSetCreator {
	mock := &MockdraDaemonSetCreator{ctrl: ctrl}
	mock.recorder = &MockdraDaemonSetCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdraDaemonSetCreator) EXPECT() *MockdraDaemonSetCreatorMockRecorder {
	return m.recorder
}

// setDRAAsDesired mocks base method.
func (m *MockdraDaemonSetCreator) setDRAAsDesired(ctx context.Context, ds *v1.DaemonSet, mod *v1beta1.Module) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "setDRAAsDesired", ctx, ds, mod)
	ret0, _ := ret[0].(error)
	return ret0
}

// setDRAAsDesired indicates an expected call of setDRAAsDesired.
func (mr *MockdraDaemonSetCreatorMockRecorder) setDRAAsDesired(ctx, ds, mod any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "setDRAAsDesired", reflect.TypeOf((*MockdraDaemonSetCreator)(nil).setDRAAsDesired), ctx, ds, mod)
}
