# permissions for end users to edit managedclustermodules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: managedclustermodule-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kernel-module-management
    app.kubernetes.io/part-of: kernel-module-management
    app.kubernetes.io/managed-by: kustomize
  name: managedclustermodule-editor-role
rules:
- apiGroups:
  - kmm.sigs.k8s.io
  resources:
  - managedclustermodules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kmm.sigs.k8s.io
  resources:
  - managedclustermodules/status
  verbs:
  - get
