apiVersion: kmm.sigs.k8s.io/v1beta1
kind: Module
metadata:
  name: kmm-ci-a
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: kmm-ci-a 

      kernelMappings:
        - regexp: 5.10.109 
          containerImage: gcr.io/myproject/kmmo:gke-3.3

          build:
            dockerfile: |
              FROM alpine:latest as builder
              ARG KERNEL_VERSION
              RUN apk add --no-cache --update \
                  abuild \
                  dpkg \ 
                  bc \
                  binutils \
                  bison \ 
                  build-base \
                  cmake \
                  diffutils \
                  elfutils-dev \
                  flex \
                  git \
                  gcc \
                  linux-headers \
                  musl-dev \
                  ncurses-dev \
                  openssl-dev \
                  python3 \
                  rsync \
                  ca-certificates \ 
                  wget

              WORKDIR /src
              RUN wget https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/snapshot/linux-${KERNEL_VERSION}.tar.gz && \
                  tar xfz linux-${KERNEL_VERSION}.tar.gz && rm -f linux-${KERNEL_VERSION}.tar.gz 
              WORKDIR /src/linux-${KERNEL_VERSION}
              RUN gunzip < /proc/config.gz > .config && \
                  yes "" | make oldconfig && make modules_prepare 
              
              WORKDIR /usr/src
              RUN git clone https://github.com/kubernetes-sigs/kernel-module-management.git && \
                  cd kernel-module-management/ci/kmm-kmod && make -C /src/linux-${KERNEL_VERSION} M=$PWD

    
              FROM alpine:latest
              RUN apk add --no-cache --update kmod
              COPY --from=builder /usr/src/kernel-module-management/ci/kmm-kmod/kmm_ci_a.ko /opt/lib/modules/${KERNEL_VERSION}/
              COPY --from=builder /usr/src/kernel-module-management/ci/kmm-kmod/kmm_ci_b.ko /opt/lib/modules/${KERNEL_VERSION}/
              RUN depmod -b /opt
  imageRepoSecret: 
    name: my-gcr-secret
  selector:  
    kubernetes.io/hostname: gke-kmmo-lab-cluster-default-pool-073sssdf-d5xl  

