apiVersion: kmm.sigs.k8s.io/v1beta1
kind: Module
metadata:
  name: kmm-ci-a
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: kmm-ci-a 

      kernelMappings:
        - literal: 5.10.109 
          containerImage: gcr.io/myproject/kmmo:gke-kmm-1.0 
          build:
            buildArgs:
              - name: CI_BUILD_ARG
                value: some-build-arg
            dockerfile: |
              ARG KERNEL_VERSION=''
              FROM debian:stable-slim as builder
              RUN apt-get update && apt-get install -y bc \
                  bison \
                  flex \
                  libelf-dev \
                  gnupg \
                  wget \
                  git \
                  make \
                  bc \
                  gcc
 
              RUN kv=${1:-v"$(uname -r | sed -E 's/\+*$//')"} && \
                  wget "https://chromium.googlesource.com/chromiumos/third_party/kernel/+archive/$kv.tar.gz" && \
                  mkdir -p /src/kernel && \
                  tar xzf "$kv.tar.gz" -C /src/kernel
              WORKDIR /src/kernel
              RUN gunzip < /proc/config.gz > .config
              RUN yes "" | make oldconfig && make prepare && make scripts
              RUN git clone https://github.com/kubernetes-sigs/kernel-module-management.git && \
                  mv kernel-module-management/ci/kmm-kmod kmm-kmod
             
              WORKDIR kmm-kmod
              RUN make -C /src/kernel

    
              ARG KERNEL_VERSION
              FROM debian:stable-slim 
              RUN apt-get update && apt-get install kmod
              COPY --from=builder /src/kernel/kmm-kmod/kmm_ci_a.ko /opt/lib/modules/${KERNEL_VERSION}/
              COPY --from=builder /src/kernel/kmm-kmod/kmm_ci_b.ko /opt/lib/modules/${KERNEL_VERSION}/
              RUN depmod -b /opt
  imageRepoSecret: 
    name: gcr-repo-secret 
  selector:  
    kubernetes.io/hostname: gke-kmmo-lab-cluster-default-pool-073sssdf-d5xl 

