name: Collect troubleshooting data

inputs:
  artifact-name:
    description: The name of the artifact for the support bundle
    required: true

description: This action fetches some troubleshooting data for KMM
runs:
  using: composite

  steps:
    - name: Install kubectl support-bundle
      run: |
        curl https://krew.sh/support-bundle | bash
        echo "PATH=${KREW_ROOT:-$HOME/.krew}/bin:$PATH" >> "$GITHUB_ENV"
      shell: bash

    - name: Collect a support bundle
      run: kubectl support-bundle -o support-bundle.tar.gz ./support/kmm.spec.yaml
      shell: bash

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: support-bundle.tar.gz
