name: Collect troubleshooting data

description: This action fetches some troubleshooting data for KMM

inputs:
  output-file:
    description: Name of the archive file
    required: true

runs:
  using: composite

  steps:
    - name: Install kubectl support-bundle
      run: |
        curl https://krew.sh/support-bundle | bash
        echo "PATH=${KREW_ROOT:-$HOME/.krew}/bin:$PATH" >> "$GITHUB_ENV"
      shell: bash

    - name: Collect a support bundle
      run: kubectl support-bundle -o ${{ inputs.output-file }} ./support/kmm.spec.yaml
      shell: bash

    - uses: actions/upload-artifact@v3
      with:
        name: support-bundle
        path: ${{ inputs.output-file }}
