name: Collect troubleshooting data

description: This action fetches some troubleshooting data for KMM

runs:
  using: composite

  steps:
    - name: Install kubectl support-bundle
      run: |
        curl https://krew.sh/support-bundle | bash
        echo "PATH=${KREW_ROOT:-$HOME/.krew}/bin:$PATH" >> "$GITHUB_ENV"
      shell: bash

    - name: Set the output file
      run: echo "OUTPUT_FILE=${{ github.job }}-support-bundle.tar.gz" >> "$GITHUB_ENV"
      shell: bash

    - name: Collect a support bundle
      run: kubectl support-bundle -o $OUTPUT_FILE ./support/kmm.spec.yaml
      shell: bash

    - uses: actions/upload-artifact@v3
      with:
        name: support-bundle
        path: ${{ env.OUTPUT_FILE }}
