#!/usr/bin/env bash

set -euxo pipefail

git remote add upstream https://github.com/kubernetes-sigs/kernel-module-management.git
git fetch upstream

commits_count=$(git rev-list --count HEAD ^upstream/main)
# When Prow is testing a PR, it is creating a branch for it but then merges it
# into the "main" branch for testing, therefore, we also get the "merge commit"
# in addition to the original commit.
if [[ ${commits_count} != 2 ]]; then
    echo '
    All PRs must contain a single commit.
    Please refer to https://github.com/kubernetes-sigs/kernel-module-management/blob/main/CONTRIBUTING.md
    '
    exit 1
fi
