#!/usr/bin/env bash

set -euxo pipefail

commits_count=$(gh pr view ${PULL_NUMBER} -R ${REPO_OWNER}/${REPO_NAME} --json commits --jq '.commits | length')

if [[ ${commits_count} != 1 ]]; then
    echo '
    All PRs must contain a single commit.
    Please refer to https://github.com/kubernetes-sigs/kernel-module-management/blob/main/CONTRIBUTING.md
    '
    exit 1
fi
