#!/usr/bin/env bash

set -euxo pipefail

make generate manifests bundle


if [[ $(git diff) ]]; then
   echo 'Please run `make generate manifests bundle` and repush'
   echo 'The following differences were found:'
   echo $(git diff)
   exit 1
fi
