#!/usr/bin/env bash

set -euxo pipefail

repo_root=$(git rev-parse --show-toplevel);
cd;
/workspace/test-infra/images/kubekins-e2e/install-bazel.sh
go install sigs.k8s.io/kubetest2@latest
go install sigs.k8s.io/kubetest2/kubetest2-gce@latest
go install sigs.k8s.io/kubetest2/kubetest2-tester-exec@latest
kubetest2 gce -v 2 \
    --repo-root ${repo_root} \
    --build \
    --up \
    --down \
    --test=exec -- ${TEST}
