#!/usr/bin/env bash

set -euxo pipefail

/workspace/test-infra/images/kubekins-e2e/install-bazel.sh
go install sigs.k8s.io/kubetest2@latest
go install sigs.k8s.io/kubetest2/kubetest2-gce@latest
go install sigs.k8s.io/kubetest2/kubetest2-tester-exec@latest

# I think --legacy-mode is required to get a vanila k8s instead of a google k8s
kubetest2 gce -v 2 \
    --repo-root /go/src/k8s.io/kubernetes \
    --legacy-mode \
    --build \
    --up \
    --down \
    --test=exec -- ${TEST}
