#!/usr/bin/env bash

set -euxo pipefail

# operator-sdk run bundle<-upgrade> doesn't support local images and the image
# has to be pushed to a remote registry.
# When the command is run, operator-sdk checks the image twice. At first, it
# validates that the image exists and then it creates a pod in the cluster
# deploying the image, therefore, the image has to be accessed from both, the
# running host and the minikube cluster.
sudo echo "127.0.0.1 host.minikube.internal" | sudo tee -a /etc/hosts

# Build the bundle from the 'main' branch
git fetch origin
git checkout -b main origin/main
go mod tidy
make bundle bundle-build bundle-push \
    VERSION="1.0.0" \
    BUNDLE_IMG=localhost:5000/kmm/kmm-bundle:current
# go back to the last branch
git checkout -f -

# Install OLM
make operator-sdk
./bin/operator-sdk olm install

# It takes some time to the operatorhubio-catalog catalogsource to get to a
# READY connection state, we need this to validate that the catalog is ready
# before installing a bundle, otherwise we might get a race condition that will
# resolved in the Subscription not being reconciled after the connecting is
# ready
timeout 3m bash -c 'until [ "$(kubectl -n olm get catalogsource/operatorhubio-catalog -o jsonpath={.status.connectionState.lastObservedState})" = "READY" ]; do sleep 5; done'

# Deploy the current bundle
./bin/operator-sdk run bundle host.minikube.internal:5000/kmm/kmm-bundle:current \
    --namespace operators \
    --use-http

# Build the new bundle
make bundle bundle-build bundle-push \
    VERSION="2.0.0" \
    IMG=host.minikube.internal:5000/kmm/kmm:local \
    SIGNER_IMG=host.minikube.internal:5000/kmm/signimage:local \
    WORKER_IMG=host.minikube.internal:5000/kmm/worker:local \
    BUNDLE_IMG=localhost:5000/kmm/kmm-bundle:local

# Upgrade to the new bundle
./bin/operator-sdk run bundle-upgrade host.minikube.internal:5000/kmm/kmm-bundle:local \
    --namespace operators \
    --use-http

