healthProbeBindAddress: :8081
metricsBindAddress: 127.0.0.1:8080
webhookPort: 9443
leaderElection:
  enabled: true
  resourceID: kmm-hub.sigs.x-k8s.io
metrics:
  enableAuthnAuthz: true
  bindAddress: 0.0.0.0:8443
  secureServing: true
