apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../manager-base

images:
- name: controller
  newName: gcr.io/k8s-staging-kmm/kernel-module-management-operator-hub
  newTag: latest

configMapGenerator:
- files:
  - controller_config.yaml
  name: manager-config

generatorOptions:
  disableNameSuffixHash: true
