# The following patch adds a directive for certmanager to inject CA into the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    # `default` and `serving-cert` may be substituted by kustomize
    cert-manager.io/inject-ca-from: default/serving-cert
  name: modules.kmm.sigs.x-k8s.io
