apiVersion: kmm.sigs.k8s.io/v1beta1
kind: ManagedClusterModule
metadata:
  labels:
    app.kubernetes.io/name: managedclustermodule
    app.kubernetes.io/instance: managedclustermodule-sample
    app.kubernetes.io/part-of: kernel-module-management
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kernel-module-management
  name: managedclustermodule-sample
spec:
  # TODO(user): Add fields here
