apiVersion: kmm.sigs.k8s.io/v1beta1
kind: Module
metadata:
  name: kmm-ci-a
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: kmm-ci-a 

      kernelMappings:
        - literal: 5.4.196-108.356.amzn2.x86_64
          containerImage: <your_aws_account>.dkr.ecr.<your_aws_region>.amazonaws.com/kmmo-lab:1.1-dkms
          build:
            buildArgs:
              - name: CI_BUILD_ARG
                value: some-build-arg
            dockerfile: |
              FROM amazonlinux as builder
              ARG KERNEL_VERSION=''
              RUN amazon-linux-extras install kernel-5.4 -y
              RUN yum -y install dkms \ 
                  kernel-headers-${KERNEL_VERSION} \
                  kernel-${KERNEL_VERSION} \
                  kernel-devel-${KERNEL_VERSION} \
                  python3 \
                  git \
                  make \
                  gcc \
                  bison \
                  flex \
                  elfutils-libelf-devel \
                  linux-headers \
                  openssl-devel \
                  xz \
                  yum-utils \
                  bc &&\
                  yum clean all

              WORKDIR /usr/src
              RUN git clone https://github.com/kubernetes-sigs/kernel-module-management.git && \
                  mv kernel-module-management/ci/kmm-kmod kmm-kmod-0.0.1 && \
                  dkms add kmm-kmod/0.0.1 && \
                  dkms build kmm-kmod/0.0.1 && \
                  dkms install kmm-kmod/0.0.1
    
              FROM amazonlinux
              ARG KERNEL_VERSION
              RUN yum -y install kmod && yum clean all
              COPY --from=builder /lib/modules/${KERNEL_VERSION}/kernel/drivers/other/kmm_ci_a/ /opt/lib/modules/${KERNEL_VERSION}/
              RUN depmod -b /opt
  imageRepoSecret: 
    name: aws-repo-secret  
  selector:  
    kubernetes.io/hostname: ip-192-168-13-20.eu-west-3.compute.internal

