apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: Module
metadata:
  name: kmm-ci-a
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: kmm-ci-a 

      kernelMappings:
        - regexp: '^.+.amzn2' 
          containerImage: <aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/kmmo-lab:kmm-2.3
          build:
            buildArgs:
              - name: CI_BUILD_ARG
                value: some-build-arg
            dockerfileConfigMap:
              name: build-module 
  imageRepoSecret: 
    name: aws-repo-secret
  selector:  
    kubernetes.io/hostname: ip-192-168-13-20.eu-west-3.compute.internal

