# permissions to emit events.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: event-recorder-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
