apiVersion: kmm.sigs.k8s.io/v1beta1
kind: Module
metadata:
  name: kmm-ci-a
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: kmm-ci-a 

      kernelMappings:
        - literal: 5.4.0-1078-gke 
          containerImage: <aws_account>.dkr.ecr.<aws_region>.amazonaws.com/kmmo-lab:1.22-gke
          build:
            buildArgs:
              - name: CI_BUILD_ARG
                value: some-build-arg
            dockerfile: |
              FROM ubuntu:20.04 as builder
              ARG KERNEL_VERSION=''
              RUN apt-get update && \ 
                  apt-get -y upgrade && \
                  apt-get install -y build-essential && \
                  apt-get install -y linux-headers-${KERNEL_VERSION} \
                  bc \
                  bison \
                  flex \
                  git \
                  libssl-dev \
                  libelf-dev \
                  python3 \
                  wget && \
                  rm -rf /var/lib/apt/lists/*

              RUN git clone https://github.com/kubernetes-sigs/kernel-module-management.git
              WORKDIR kernel-module-management/ci/kmm-kmod 
              RUN make 
              FROM ubuntu:20.04 
              ARG KERNEL_VERSION
              RUN apt-get -y update && apt-get -y install kmod && \
                  rm -rf /var/lib/apt/lists/*
              COPY --from=builder kernel-module-management/ci/kmm-kmod/kmm_ci_a.ko /opt/lib/modules/${KERNEL_VERSION}/
              RUN depmod -b /opt
  imageRepoSecret: 
    name: aws-repo-secret  
  selector:  
    kubernetes.io/hostname: gke-kmmo-lab-cluster-default-pool-073f8f9f-9z5s 

