apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

## Append samples you want in your CSV to this file as resources ##
resources:
  - hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
