// Code generated by MockGen. DO NOT EDIT.
// Source: imagemounter.go
//
// Generated by this command:
//
//	mockgen -source=imagemounter.go -package=worker -destination=mock_imagemounter.go
//
// Package worker is a generated GoMock package.
package worker

import (
	context "context"
	reflect "reflect"

	v1beta1 "github.com/kubernetes-sigs/kernel-module-management/api/v1beta1"
	gomock "go.uber.org/mock/gomock"
)

// MockImageMounter is a mock of ImageMounter interface.
type MockImageMounter struct {
	ctrl     *gomock.Controller
	recorder *MockImageMounterMockRecorder
}

// MockImageMounterMockRecorder is the mock recorder for MockImageMounter.
type MockImageMounterMockRecorder struct {
	mock *MockImageMounter
}

// NewMockImageMounter creates a new mock instance.
func NewMockImageMounter(ctrl *gomock.Controller) *MockImageMounter {
	mock := &MockImageMounter{ctrl: ctrl}
	mock.recorder = &MockImageMounterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageMounter) EXPECT() *MockImageMounterMockRecorder {
	return m.recorder
}

// MountImage mocks base method.
func (m *MockImageMounter) MountImage(ctx context.Context, imageName string, cfg *v1beta1.ModuleConfig) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MountImage", ctx, imageName, cfg)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MountImage indicates an expected call of MountImage.
func (mr *MockImageMounterMockRecorder) MountImage(ctx, imageName, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MountImage", reflect.TypeOf((*MockImageMounter)(nil).MountImage), ctx, imageName, cfg)
}
