apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: kmm-operator-system

namePrefix: kmm-operator-hub-

# Labels to add to all resources and selectors.
commonLabels:
  app.kubernetes.io/name: kmm-hub
  app.kubernetes.io/component: kmm-hub
  app.kubernetes.io/part-of: kmm

resources:
- ../deploy-hub

components:
- ../webhook-cert

replacements:
  # Replacements below adjust the value of the cert-manager.io/inject-ca-from annotation in CRDs and webhook objects.
  - source:
      kind: Certificate
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: CustomResourceDefinition
        fieldPaths:
          - metadata.annotations.[cert-manager.io/inject-ca-from]
        options:
          create: true
          delimiter: /
      - select:
          kind: ValidatingWebhookConfiguration
        fieldPaths:
          - metadata.annotations.[cert-manager.io/inject-ca-from]
        options:
          create: true
          delimiter: /
  - source:
      kind: Certificate
      fieldPath: metadata.name
    targets:
      - select:
          kind: CustomResourceDefinition
        fieldPaths:
          - metadata.annotations.[cert-manager.io/inject-ca-from]
        options:
          create: true
          delimiter: /
          index: 1
      - select:
          kind: ValidatingWebhookConfiguration
        fieldPaths:
          - metadata.annotations.[cert-manager.io/inject-ca-from]
        options:
          create: true
          delimiter: /
          index: 1
  # Replacements below adjust the DNS names of the webhook certificate based on the service name.
  - source:
      kind: Service
      name: webhook-service
      fieldPath: metadata.name
    targets:
      - select:
          kind: Certificate
        fieldPaths:
          - spec.dnsNames.*
        options:
          delimiter: .
  - source:
      kind: Service
      name: webhook-service
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: Certificate
        fieldPaths:
          - spec.dnsNames.*
        options:
          delimiter: .
          index: 1

configurations:
  - kustomizeconfig.yaml
