---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/name: validatingwebhookconfiguration
    app.kubernetes.io/instance: validating-webhook-configuration
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: kernel-module-management
    app.kubernetes.io/part-of: kernel-module-management
    app.kubernetes.io/managed-by: kustomize
  name: validating-webhook-configuration
  annotations:
    # `default` and `serving-cert` may be substituted by kustomize
    cert-manager.io/inject-ca-from: default/serving-cert
