// Code generated by MockGen. DO NOT EDIT.
// Source: metrics.go

// Package metrics is a generated GoMock package.
package metrics

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockMetrics) Register() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register")
}

// Register indicates an expected call of Register.
func (mr *MockMetricsMockRecorder) Register() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockMetrics)(nil).Register))
}

// SetExistingKMMOModules mocks base method.
func (m *MockMetrics) SetExistingKMMOModules(value int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetExistingKMMOModules", value)
}

// SetExistingKMMOModules indicates an expected call of SetExistingKMMOModules.
func (mr *MockMetricsMockRecorder) SetExistingKMMOModules(value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetExistingKMMOModules", reflect.TypeOf((*MockMetrics)(nil).SetExistingKMMOModules), value)
}
