// Code generated by MockGen. DO NOT EDIT.
// Source: helper.go

// Package sign is a generated GoMock package.
package sign

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1beta1 "github.com/kubernetes-sigs/kernel-module-management/api/v1beta1"
)

// MockHelper is a mock of Helper interface.
type MockHelper struct {
	ctrl     *gomock.Controller
	recorder *MockHelperMockRecorder
}

// MockHelperMockRecorder is the mock recorder for MockHelper.
type MockHelperMockRecorder struct {
	mock *MockHelper
}

// NewMockHelper creates a new mock instance.
func NewMockHelper(ctrl *gomock.Controller) *MockHelper {
	mock := &MockHelper{ctrl: ctrl}
	mock.recorder = &MockHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHelper) EXPECT() *MockHelperMockRecorder {
	return m.recorder
}

// GetRelevantSign mocks base method.
func (m *MockHelper) GetRelevantSign(mod v1beta1.Module, km v1beta1.KernelMapping) *v1beta1.Sign {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelevantSign", mod, km)
	ret0, _ := ret[0].(*v1beta1.Sign)
	return ret0
}

// GetRelevantSign indicates an expected call of GetRelevantSign.
func (mr *MockHelperMockRecorder) GetRelevantSign(mod, km interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelevantSign", reflect.TypeOf((*MockHelper)(nil).GetRelevantSign), mod, km)
}
