apiVersion: v1
kind: ConfigMap
metadata:
  name: kmm-kmod-dockerfile
data:
  dockerfile: |
    FROM registry.minikube/kmm-base:local

    ARG CI_BUILD_ARG
    ARG KERNEL_VERSION
    ARG WITH_DEFAULT_VALUE=default-value

    RUN cat /run/secrets/build-secret/ci-build-secret > /ci-build-secret
    RUN echo $CI_BUILD_ARG > /build-arg
    RUN echo $KERNEL_VERSION > /kernel-version
    RUN echo $WITH_DEFAULT_VALUE > /default-value
