---
apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: Module
metadata:
  name: kmm-ci-device-plugin-only
spec:
  devicePlugin:
    container:
      image: registry.k8s.io/pause:3.10
  selector:
    kubernetes.io/hostname: minikube
