---
apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: Module
metadata:
  name: kmm-ci
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: kmm_ci_a
      kernelMappings:
        - regexp: '^.+$'
          containerImage: host.minikube.internal:5000/kmm-kmod:$KERNEL_FULL_VERSION
          registryTLS:
            insecure: true
          build:
            baseImageRegistryTLS:
              insecure: true
            secrets:
              - name: build-secret
            dockerfileConfigMap:
              name: kmm-kmod-dockerfile
            # Optional. If kanikoParams.tag is empty, the default value will be: 'latest'
            kanikoParams:
              tag: "debug"
  selector:
    kubernetes.io/hostname: minikube
