apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Labels to add to all resources and selectors.

# These resources constitute the fully configured set of manifests
# used to generate the 'manifests/' directory in a bundle.
resources:
- bases/kernel-module-management.clusterserviceversion.yaml
- ../olm
- ../samples
- ../scorecard
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: kmm
    app.kubernetes.io/name: kmm
    app.kubernetes.io/part-of: kmm
