name: Docs

on: [pull_request]

jobs:
  build-compare:
    name: Build and compare docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          cache: pip
          python-version: 3.x

      - name: Install mkdocs
        run: pip install -r docs/requirements.txt

      - name: Install Java for PlantUML
        run: |
          sudo apt update
          sudo apt install -y --install-suggests default-jre fonts-noto
          sudo fc-cache -fs

      - name: Build the docs site
        run: make docs

      - name: Check if the output directory changed
        run: |
          git add -N docs/site

          if ! git diff --quiet docs/site/ ':!docs/site/index.html' ':!docs/site/sitemap.xml*'; then
            echo 'Changes detected; please run make -C docs.'
            git diff docs/site ':!docs/site/index.html' ':!docs/site/sitemap.xml*'
            exit 1
          fi

      - name: Upload the docs directory if changes were detected
        uses: actions/upload-artifact@v3
        with:
          name: docs-site
          path: docs/site
        if: ${{ failure() }}
