name: Test and upload to Codecov

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test-build:
    name: Test and upload to Codecov

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Generate code
      run: make generate

    - name: Run tests
      run: make unit-test

    - name: Upload the coverage to Codecov
      uses: codecov/codecov-action@v5
