name: Test and upload to Codecov

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test-build:
    name: Test and upload to Codecov

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
      with:
        go-version: '1.25'

    - name: Generate code
      run: make generate

    - name: Run tests
      run: make unit-test

    - name: Upload the coverage to Codecov
      uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe # v5
