// Code generated by MockGen. DO NOT EDIT.
// Source: workerpodmanager.go
//
// Generated by this command:
//
//	mockgen -source=workerpodmanager.go -package=pod -destination=mock_workerpodmanager.go
//
// Package pod is a generated GoMock package.
package pod

import (
	context "context"
	reflect "reflect"

	v1beta1 "github.com/kubernetes-sigs/kernel-module-management/api/v1beta1"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockWorkerPodManager is a mock of WorkerPodManager interface.
type MockWorkerPodManager struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerPodManagerMockRecorder
}

// MockWorkerPodManagerMockRecorder is the mock recorder for MockWorkerPodManager.
type MockWorkerPodManagerMockRecorder struct {
	mock *MockWorkerPodManager
}

// NewMockWorkerPodManager creates a new mock instance.
func NewMockWorkerPodManager(ctrl *gomock.Controller) *MockWorkerPodManager {
	mock := &MockWorkerPodManager{ctrl: ctrl}
	mock.recorder = &MockWorkerPodManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerPodManager) EXPECT() *MockWorkerPodManagerMockRecorder {
	return m.recorder
}

// CreateLoaderPod mocks base method.
func (m *MockWorkerPodManager) CreateLoaderPod(ctx context.Context, nmc client.Object, nms *v1beta1.NodeModuleSpec) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLoaderPod", ctx, nmc, nms)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLoaderPod indicates an expected call of CreateLoaderPod.
func (mr *MockWorkerPodManagerMockRecorder) CreateLoaderPod(ctx, nmc, nms any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLoaderPod", reflect.TypeOf((*MockWorkerPodManager)(nil).CreateLoaderPod), ctx, nmc, nms)
}

// CreateUnloaderPod mocks base method.
func (m *MockWorkerPodManager) CreateUnloaderPod(ctx context.Context, nmc client.Object, nms *v1beta1.NodeModuleStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUnloaderPod", ctx, nmc, nms)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUnloaderPod indicates an expected call of CreateUnloaderPod.
func (mr *MockWorkerPodManagerMockRecorder) CreateUnloaderPod(ctx, nmc, nms any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUnloaderPod", reflect.TypeOf((*MockWorkerPodManager)(nil).CreateUnloaderPod), ctx, nmc, nms)
}

// DeletePod mocks base method.
func (m *MockWorkerPodManager) DeletePod(ctx context.Context, pod *v1.Pod) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePod", ctx, pod)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePod indicates an expected call of DeletePod.
func (mr *MockWorkerPodManagerMockRecorder) DeletePod(ctx, pod any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePod", reflect.TypeOf((*MockWorkerPodManager)(nil).DeletePod), ctx, pod)
}

// GetConfigAnnotation mocks base method.
func (m *MockWorkerPodManager) GetConfigAnnotation(p *v1.Pod) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigAnnotation", p)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetConfigAnnotation indicates an expected call of GetConfigAnnotation.
func (mr *MockWorkerPodManagerMockRecorder) GetConfigAnnotation(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigAnnotation", reflect.TypeOf((*MockWorkerPodManager)(nil).GetConfigAnnotation), p)
}

// GetTolerationsAnnotation mocks base method.
func (m *MockWorkerPodManager) GetTolerationsAnnotation(p *v1.Pod) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTolerationsAnnotation", p)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetTolerationsAnnotation indicates an expected call of GetTolerationsAnnotation.
func (mr *MockWorkerPodManagerMockRecorder) GetTolerationsAnnotation(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTolerationsAnnotation", reflect.TypeOf((*MockWorkerPodManager)(nil).GetTolerationsAnnotation), p)
}

// GetWorkerPod mocks base method.
func (m *MockWorkerPodManager) GetWorkerPod(ctx context.Context, podName, namespace string) (*v1.Pod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkerPod", ctx, podName, namespace)
	ret0, _ := ret[0].(*v1.Pod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkerPod indicates an expected call of GetWorkerPod.
func (mr *MockWorkerPodManagerMockRecorder) GetWorkerPod(ctx, podName, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkerPod", reflect.TypeOf((*MockWorkerPodManager)(nil).GetWorkerPod), ctx, podName, namespace)
}

// HashAnnotationDiffer mocks base method.
func (m *MockWorkerPodManager) HashAnnotationDiffer(p1, p2 *v1.Pod) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashAnnotationDiffer", p1, p2)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HashAnnotationDiffer indicates an expected call of HashAnnotationDiffer.
func (mr *MockWorkerPodManagerMockRecorder) HashAnnotationDiffer(p1, p2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashAnnotationDiffer", reflect.TypeOf((*MockWorkerPodManager)(nil).HashAnnotationDiffer), p1, p2)
}

// IsLoaderPod mocks base method.
func (m *MockWorkerPodManager) IsLoaderPod(p *v1.Pod) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLoaderPod", p)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsLoaderPod indicates an expected call of IsLoaderPod.
func (mr *MockWorkerPodManagerMockRecorder) IsLoaderPod(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLoaderPod", reflect.TypeOf((*MockWorkerPodManager)(nil).IsLoaderPod), p)
}

// IsUnloaderPod mocks base method.
func (m *MockWorkerPodManager) IsUnloaderPod(p *v1.Pod) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUnloaderPod", p)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsUnloaderPod indicates an expected call of IsUnloaderPod.
func (mr *MockWorkerPodManagerMockRecorder) IsUnloaderPod(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUnloaderPod", reflect.TypeOf((*MockWorkerPodManager)(nil).IsUnloaderPod), p)
}

// ListWorkerPodsOnNode mocks base method.
func (m *MockWorkerPodManager) ListWorkerPodsOnNode(ctx context.Context, nodeName string) ([]v1.Pod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWorkerPodsOnNode", ctx, nodeName)
	ret0, _ := ret[0].([]v1.Pod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWorkerPodsOnNode indicates an expected call of ListWorkerPodsOnNode.
func (mr *MockWorkerPodManagerMockRecorder) ListWorkerPodsOnNode(ctx, nodeName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWorkerPodsOnNode", reflect.TypeOf((*MockWorkerPodManager)(nil).ListWorkerPodsOnNode), ctx, nodeName)
}

// LoaderPodTemplate mocks base method.
func (m *MockWorkerPodManager) LoaderPodTemplate(ctx context.Context, nmc client.Object, nms *v1beta1.NodeModuleSpec) (*v1.Pod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoaderPodTemplate", ctx, nmc, nms)
	ret0, _ := ret[0].(*v1.Pod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoaderPodTemplate indicates an expected call of LoaderPodTemplate.
func (mr *MockWorkerPodManagerMockRecorder) LoaderPodTemplate(ctx, nmc, nms any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoaderPodTemplate", reflect.TypeOf((*MockWorkerPodManager)(nil).LoaderPodTemplate), ctx, nmc, nms)
}

// UnloaderPodTemplate mocks base method.
func (m *MockWorkerPodManager) UnloaderPodTemplate(ctx context.Context, nmc client.Object, nms *v1beta1.NodeModuleStatus) (*v1.Pod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnloaderPodTemplate", ctx, nmc, nms)
	ret0, _ := ret[0].(*v1.Pod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnloaderPodTemplate indicates an expected call of UnloaderPodTemplate.
func (mr *MockWorkerPodManagerMockRecorder) UnloaderPodTemplate(ctx, nmc, nms any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnloaderPodTemplate", reflect.TypeOf((*MockWorkerPodManager)(nil).UnloaderPodTemplate), ctx, nmc, nms)
}
